### PR TITLE
Decouple planning from execution

### PR DESCRIPTION
**Pull request by edrevo**
Big PR... I got carried away, sorry!

Here's what this PR does: it takes a step in the direction of https://github.com/ballista-compute/ballista/issues/463 and decouples the planning phase from the execution phase.

When a client submits a query/plan, the only thing the scheduler does is calculate the stages and saves them to etcd. That enables submitting queries even when there are no executors available: once an executor comes online the job will transition to the Running state. It also enables adding more executors to the cluster and the scheduler will be able to dynamically send them whichever tasks are ready to be run.

How are tasks run? The executor registration endpoint in the scheduler has been renamed to "poll_work", and it now does various things:

1. It works as a heartbeat for executor liveness
2. It allows executors to report the status of the tasks that have finished since the last call to poll_work
3. It allows executors to request more work from the scheduler

The changes in the scheduler have been made keeping in mind that we should support a scheduler cluster. I haven't tested it, but right now I'm basically doing a big fat distributed lock through etcd, which is very inefficient but also very easy to get right 😂 

The bad parts of this PR:
1. ~No unit tests.~ (added!)
2. ~There seems to be a big perf hit when using etcd. Query 1 takes 5 seconds on standalone and 10 seconds with etcd. Not sure why. The scheduler code can still be heavily optimized (I've preferred correctess and simplicity as a first approach), but that huge impact is somewhat surprising.~ (see next comment)

### CODE REVIEW

**Comment by edrevo** [comment]
thanks @andygrove for the pointer on the poll period. if i reduce it to 100msecs, then the difference between etcd and standalone is neglegible:

```
etcd:
Query 1 iteration 0 took 5050.4 ms
Query 1 avg time: 5050.42 ms

standalone:
Query 1 iteration 0 took 5043.0 ms
Query 1 avg time: 5042.96 ms
```

**Comment by andygrove** [comment]
This is very exciting. I will make time to review this over the weekend!

**Comment by edrevo** [comment]
Merge conflicts fixed

**Comment by edrevo** [comment]
merge conflicts fixed agaon

**Comment by andygrove** [comment]
Thanks @edrevo I am testing this now

**Comment by andygrove** [comment]
I pulled the latest from main and then merged in this PR locally. Integration tests pass but benchmarks hang when run against a large partitioned Parquet data set. I suppose that tells us that we need better integration tests. I will see if I can reproduce the failure in the integration tests.

I will hold off merging any other PRs until we get this one in.

One other thing I noticed is that only one partition gets passed to `ExecutePartitions` rather than passing multiple partitions (which was a recent improvement since you started on this PR, so it is not too surprising).

**Comment by andygrove** [comment]
I can only reproduce the issue with a large data set (100GB) :disappointed: so that doesn't help with the integration tests.

It looks like the query completes but somehow the scheduler doesn't recognize that the query completed? Perhaps a future not being collected correctly? I will keep looking ...

**Comment by edrevo** [comment]
Can you give me instructions on how to reproduce the issue?

**Comment by andygrove** [comment]
I ran the tpch benchmarks against the SF=100 data set, which I had converted to Parquet with 8 partitions for each table. You can follow the instructions here: https://github.com/apache/arrow/tree/master/rust/benchmarks

I am going to be working on benchmark automation this week, to make it easier to run these benchmarks at scale.

**Comment by edrevo** [comment]
@andygrove, I am not able to reproduce the hang. I was finally able to generate the 100GB of data and converting it to parquet after the fixes I made to DataFusion, but the tpch queries either:

1. work fine
2. die due to oom

So no hang, unfortunately. Do you remember which query caused the hang for you?

**Comment by andygrove** [comment]
Sorry I do not remember. I will retest with the fixes.

**Comment by andygrove** [comment]
I am testing this now and still seeing the issue with query 1 where it never completes. I am now going to start adding debug logging and see if I can figure out what the issue is.

**Comment by andygrove** [comment]
I see this output in scheduler:

```
[2021-02-28T17:27:37Z INFO  ballista::scheduler] Sending new task to f77baaf3-439e-4f06-842a-451ccfc898dd: job jUPVSFW / stage 1 / partition 0
[2021-02-28T17:27:38Z INFO  ballista::scheduler] Sending new task to f77baaf3-439e-4f06-842a-451ccfc898dd: job jUPVSFW / stage 1 / partition 3
[2021-02-28T17:27:38Z INFO  ballista::scheduler] Sending new task to f77baaf3-439e-4f06-842a-451ccfc898dd: job jUPVSFW / stage 1 / partition 7
[2021-02-28T17:27:38Z INFO  ballista::scheduler] Sending new task to f77baaf3-439e-4f06-842a-451ccfc898dd: job jUPVSFW / stage 1 / partition 6
[2021-02-28T17:27:38Z INFO  ballista::scheduler] Sending new task to f77baaf3-439e-4f06-842a-451ccfc898dd: job jUPVSFW / stage 1 / partition 2
[2021-02-28T17:27:39Z INFO  ballista::scheduler] Sending new task to f77baaf3-439e-4f06-842a-451ccfc898dd: job jUPVSFW / stage 1 / partition 1
[2021-02-28T17:27:39Z INFO  ballista::scheduler] Sending new task to f77baaf3-439e-4f06-842a-451ccfc898dd: job jUPVSFW / stage 1 / partition 4
[2021-02-28T17:27:39Z INFO  ballista::scheduler] Sending new task to f77baaf3-439e-4f06-842a-451ccfc898dd: job jUPVSFW / stage 1 / partition 5
```

I see each executor successfully complete the tasks:

```
[2021-02-28T17:27:50Z INFO  executor] DONE WITH CURRENT TASK: Ok([ExecutePartitionResult { path: "/tmp/.tmp4TWIMG/jUPVSFW/1/7/data.arrow", stats: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 } }])
[2021-02-28T17:27:50Z INFO  executor] Current task finished
[2021-02-28T17:27:51Z INFO  ballista::executor::flight_service] Executed partition 2 in 12 seconds. Statistics: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 }
[2021-02-28T17:27:51Z INFO  executor] DONE WITH CURRENT TASK: Ok([ExecutePartitionResult { path: "/tmp/.tmp4TWIMG/jUPVSFW/1/2/data.arrow", stats: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 } }])
[2021-02-28T17:27:51Z INFO  executor] Current task finished
[2021-02-28T17:27:51Z INFO  ballista::executor::flight_service] Executed partition 3 in 13 seconds. Statistics: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 }
[2021-02-28T17:27:51Z INFO  executor] DONE WITH CURRENT TASK: Ok([ExecutePartitionResult { path: "/tmp/.tmp4TWIMG/jUPVSFW/1/3/data.arrow", stats: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 } }])
[2021-02-28T17:27:51Z INFO  ballista::executor::flight_service] Executed partition 0 in 13 seconds. Statistics: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 }
[2021-02-28T17:27:51Z INFO  executor] DONE WITH CURRENT TASK: Ok([ExecutePartitionResult { path: "/tmp/.tmp4TWIMG/jUPVSFW/1/0/data.arrow", stats: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 } }])
[2021-02-28T17:27:51Z INFO  executor] Current task finished
[2021-02-28T17:27:52Z INFO  ballista::executor::flight_service] Executed partition 6 in 13 seconds. Statistics: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 }
[2021-02-28T17:27:52Z INFO  executor] DONE WITH CURRENT TASK: Ok([ExecutePartitionResult { path: "/tmp/.tmp4TWIMG/jUPVSFW/1/6/data.arrow", stats: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 } }])
[2021-02-28T17:27:52Z INFO  executor] Current task finished
[2021-02-28T17:27:52Z INFO  ballista::executor::flight_service] Executed partition 1 in 13 seconds. Statistics: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 }
[2021-02-28T17:27:52Z INFO  executor] DONE WITH CURRENT TASK: Ok([ExecutePartitionResult { path: "/tmp/.tmp4TWIMG/jUPVSFW/1/1/data.arrow", stats: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 } }])
[2021-02-28T17:27:52Z INFO  executor] Current task finished
[2021-02-28T17:27:52Z INFO  ballista::executor::flight_service] Executed partition 5 in 12 seconds. Statistics: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 }
[2021-02-28T17:27:52Z INFO  executor] DONE WITH CURRENT TASK: Ok([ExecutePartitionResult { path: "/tmp/.tmp4TWIMG/jUPVSFW/1/5/data.arrow", stats: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 } }])
[2021-02-28T17:27:52Z INFO  executor] Current task finished
[2021-02-28T17:27:53Z INFO  ballista::executor::flight_service] Executed partition 4 in 13 seconds. Statistics: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 }
[2021-02-28T17:27:53Z INFO  executor] DONE WITH CURRENT TASK: Ok([ExecutePartitionResult { path: "/tmp/.tmp4TWIMG/jUPVSFW/1/4/data.arrow", stats: PartitionStats { num_rows: 4, num_batches: 1, num_bytes: 2032, null_count: 0 } }])
[2021-02-28T17:27:53Z INFO  executor] Current task finished
```

Nothing happens after this.

**Review by andygrove — APPROVED** [review]

**Comment by andygrove** [comment]
All working now. This does regress performance since each executor is one concurrent task.

**Comment by edrevo** [comment]
Yeah, the PR to send several partitions in parallel happened after this PR was opened.

**Comment by edrevo** [comment]
However, this PR will allows for concurrent stage execution if you have enough executors, so it regresses perf with 1 executor, but improves perf with multiple executors.

**Comment by edrevo** [comment]
Python binding lint is broken in main. Merging.

**Pull request merged**
