### PR TITLE
[WIP] Cleanup async

### PR DESCRIPTION
**Pull request by hwchen**
Whoops, looks like I need to rebase.

There's also some things I want to clarify, and then there's also some minor things (like a `thread::sleep`) I want to clean up.

And finally, I would love to get this branch running in a k8 cluster locally, but haven't quite figured it out.

Regardless, here's the code so we can discuss.

### CODE REVIEW

**Comment by andygrove** [comment]
This is looking good @hwchen ... hopefully, I'll be done with refactoring the scheduler and executor this weekend so I would hold off until next week before rebasing. Another option would be to try breaking this down into some smaller PRs.

**Comment by andygrove** [comment]
@hwchen I have finished with the scheduler/executor refactoring now.

**Comment by andygrove** [comment]
Thanks for helping with this @hwchen but I am closing this for now. I plan on updating Ballista to use Arrow 2.0.0 soon and will be able to re-use the Arrow physical plans which now support async.

**Comment by hwchen** [comment]
No worries, sounds good!

**Pull request closed without merging**
