### PR TITLE
Arrow version bump

### PR DESCRIPTION
**Pull request by morpheyesh**
@andygrove I am currently getting some mismatch types error in the executors due to this version bump. Looking into this atm. Am I missing something?

### CODE REVIEW

**Comment by andygrove** [comment]
> @andygrove I am currently getting some mismatch types error in the executors due to this version bump. Looking into this atm. Am I missing something?

If you change the rev to `c3b972c` it should work

**Comment by andygrove** [comment]
@morpheyesh It looks like you were trying to downgrade to an older Arrow release?

**Comment by andygrove** [comment]
I pulled this branch and had to add `use datafusion::datasource::CsvReadOptions;` to tpch main.rs to get it to compile

**Comment by morpheyesh** [comment]
Yes, I just checked Arrow. My bad. Closing this :)

**Pull request closed without merging**
