### PR TITLE
Make DistributedPlanner::execute_query_stage concurrent

### PR DESCRIPTION
**Pull request by j4ckcyw**
`cargo test` passed

### CODE REVIEW

**Comment by j4ckcyw** [comment]
It looked like there is no test written for the distributed planner yet. Let me know if there are other validations I should be doing other than cargo test. This change looks safe to me since this is about refactoring and rustc has been very good at catching my concurrency bugs.

**Review by andygrove — APPROVED** [review]

**Comment by andygrove** [comment]
@j4ckcyw See https://github.com/ballista-compute/ballista/pull/523 for integration tests. I hope to merge this shortly.

**Comment by andygrove** [comment]
@j4ckcyw Looks like you need to run `cargo fmt`

**Comment by j4ckcyw** [comment]
> 
> 
> @j4ckcyw Looks like you need to run `cargo fmt`

done.

**Comment by andygrove** [comment]
I ran the integration tests locally after pulling this change into my branch and it passed :tada:

**Pull request merged**
